version: 2.1

jobs:
  ios:
    macos: # indicate that we are using the macOS executor
      xcode: 14.3.1
    environment:
      IOS_VERSION: 16.4
      DEVICE_NAME: iPhone 14 Pro
    steps:
      - checkout
      - run:
          name: Install Java JDK
          command: |
            brew tap AdoptOpenJDK/openjdk
            brew install --cask adoptopenjdk8
      # Install Node.js and dependencies
      - run:
          name: Install Node.js
          command: |
            brew install node
            node -v
            npm -v
      - run:
          name: Install Dependencies
          command: npm install
      # Install Appium
      - run:
          name: Install Appium
          command: |
            npm install -g appium
            appium -v
      # Start Appium Server
      - run:
          name: Start Appium Server
          command: |
            appium &
            sleep 5
      # Run Tests
      - run:
          name: Run Tests
          command: |
            npx wdio config/wdio.conf.js
workflows:
  build_and_test:
    jobs:
      - ios
