version: 2.1

jobs:
  ios:
    macos: # indicate that we are using the macOS executor
      xcode: 14.3.1
    environment:
      IOS_VERSION: 16.4
      DEVICE_NAME: iPhone 14 Pro
    steps:
      - checkout
      - run:
          name: Install Homebrew
          command: |
            if ! which brew; then
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            fi
      - run:
          name: Install Node.js 20.15.0
          command: |
            brew install node@20
      - run:
          name: Verify Node.js Installation
          command: |
            node -v
            npm -v
      - run:
          name: Install Dependencies
          command: npm install
      # Install Appium
      - run:
          name: Install Appium
          command: |
            npm install -g appium
            appium -v
      # Start Appium Server
      - run:
          name: Start Appium Server
          command: |
            appium &
            sleep 5
      # Run Tests
      - run:
          name: Run Tests
          command: |
            npx wdio config/wdio.conf.js
workflows:
  build_and_test:
    jobs:
      - ios
