version: 2.1

jobs:
  ios:
    macos: # indicate that we are using the macOS executor
      xcode: 14.3.1
    environment:
      IOS_VERSION: 16.4
      DEVICE_NAME: iPhone 14 Pro
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            source ~/.nvm/nvm.sh
            nvm install 20.15.0  # Replace '16' with the Node.js version you need
            nvm use 20.15.0

      # Optionally install a specific npm version after Node.js
      - run:
          name: Install Specific npm Version
          command: |
            npm install -g npm@8  # Replace '8' with your required npm version
            npm -v  # Verify the npm version

      # Install Appium
      - run:
          name: Install Appium
          command: |
            npm install -g appium
            appium -v
      # Start Appium Server
      - run:
          name: Start Appium Server
          command: |
            appium &
            sleep 5
      # Run Tests
      - run:
          name: Run Tests
          command: |
            npx wdio config/wdio.conf.js
workflows:
  build_and_test:
    jobs:
      - ios
