version: 2.1

jobs:
  ios:
    macos: # indicate that we are using the macOS executor
      xcode: 14.3.1
    environment:
      IOS_VERSION: 16.4
      DEVICE_NAME: iPhone 14 Pro
    steps:
      - checkout
      - run:
          name: Uninstall all Node.js versions via nvm
          command: |
            # Install nvm if it's not already installed
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            source ~/.nvm/nvm.sh

            # Uninstall all Node.js versions managed by nvm
            nvm ls | grep -o 'v[0-9]*\.[0-9]*\.[0-9]*' | xargs -I {} nvm uninstall {}

            # Clean up global node modules
            sudo rm -rf /usr/local/lib/node_modules

            # Remove Node.js binaries (if installed manually or system-wide)
            sudo rm -rf /usr/local/bin/node /usr/local/bin/npm

            # Remove nvm (if you want to fully clean nvm as well)
            rm -rf ~/.nvm
            rm -f ~/.bash_profile ~/.zshrc ~/.profile

      - run:
          name: Install Node.js 20.15.0 and npm directly
          command: |
            # Download Node.js 20.15.0 binaries
            curl -O https://nodejs.org/dist/v20.15.0/node-v20.15.0-darwin-x64.tar.gz

            # Extract the downloaded file
            tar -xzf node-v20.15.0-darwin-x64.tar.gz

            # Move Node.js binaries to a system location
            sudo mv node-v20.15.0-darwin-x64 /usr/local/node-v20.15.0
            sudo ln -s /usr/local/node-v20.15.0/bin/node /usr/local/bin/node
            sudo ln -s /usr/local/node-v20.15.0/bin/npm /usr/local/bin/npm
            sudo ln -s /usr/local/node-v20.15.0/bin/npx /usr/local/bin/npx
      - run:
          name: Verify Node.js Installation
          command: |
            node -v
            npm -v
      - run:
          name: Install Dependencies
          command: npm install
      # Install Appium
      - run:
          name: Install Appium
          command: |
            npm install -g appium
            appium -v
      # Start Appium Server
      - run:
          name: Start Appium Server
          command: |
            appium &
            sleep 5
      # Run Tests
      - run:
          name: Run Tests
          command: |
            nvm use 20.2.0
            npx wdio config/wdio.conf.js
workflows:
  build_and_test:
    jobs:
      - ios
