version: 2.1

jobs:
  ios:
    macos: # indicate that we are using the macOS executor
      xcode: 14.3.1
    environment:
      IOS_VERSION: 16.4
      DEVICE_NAME: iPhone 14 Pro
    steps:
      - checkout
      - run:
          name: Clean up all Node.js versions
          command: |
            # Remove NVM installations
            rm -rf ~/.nvm
            # Remove Homebrew installation of Node.js
            brew uninstall node
            brew cleanup
            # Remove any Node.js binaries installed directly
            sudo rm -rf /usr/local/node-v*
            sudo rm -f /usr/local/bin/node
            sudo rm -f /usr/local/bin/npm
            sudo rm -f /usr/local/bin/npx

            # Verify removal
            node -v  # Should not return a version
            npm -v   # Should not return a version
      - run:
          name: Install Node.js 20.15.0 and npm directly
          command: |
            # Download Node.js 20.15.0 binaries
            curl -O https://nodejs.org/dist/v20.15.0/node-v20.15.0-darwin-x64.tar.gz

            # Extract the downloaded file
            tar -xzf node-v20.15.0-darwin-x64.tar.gz

            # Move Node.js binaries to a system location
            sudo mv node-v20.15.0-darwin-x64 /usr/local/node-v20.15.0
            sudo ln -s /usr/local/node-v20.15.0/bin/node /usr/local/bin/node
            sudo ln -s /usr/local/node-v20.15.0/bin/npm /usr/local/bin/npm
            sudo ln -s /usr/local/node-v20.15.0/bin/npx /usr/local/bin/npx

            # Verify the installation of Node.js and npm
            node -v  # Should show v20.15.0
            npm -v   # Should show the npm version bundled with Node.js
      - run:
          name: Install Dependencies
          command: npm install
      # Install Appium
      - run:
          name: Install Appium
          command: |
            npm install -g appium
            appium -v
      # Start Appium Server
      - run:
          name: Start Appium Server
          command: |
            appium &
            sleep 5
      # Run Tests
      - run:
          name: Run Tests
          command: |
            npx wdio config/wdio.conf.js
workflows:
  build_and_test:
    jobs:
      - ios
