version: 2.1

jobs:
  ios:
    macos: # indicate that we are using the macOS executor
      xcode: 14.3.1
    environment:
      IOS_VERSION: 16.4
      DEVICE_NAME: iPhone 14 Pro
    steps:
      - checkout
      - run:
          name: Install nvm
          command: |
            # Install nvm
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            source ~/.nvm/nvm.sh  # Ensure nvm is sourced
      - run:
          name: Install Node.js v20.15.0 and set it as active
          command: |
            # Load nvm
            source ~/.nvm/nvm.sh
            # Install Node.js version 20.15.0
            nvm install 20.15.0
            # Set it as the active version
            nvm use 20.15.0
            # Verify the active Node.js version
            node -v
      - run:
          name: Install Dependencies
          command: npm install
      # Install Appium
      - run:
          name: Install Appium
          command: |
            npm install -g appium
            appium -v
      # Start Appium Server
      - run:
          name: Start Appium Server
          command: |
            appium &
            sleep 5
      # Run Tests
      - run:
          name: Run Tests
          command: |
            nvm use 20.15.0
            npx wdio config/wdio.conf.js
workflows:
  build_and_test:
    jobs:
      - ios
