version: 2.1

jobs:
  ios:
    macos: # indicate that we are using the macOS executor
      xcode: 14.3.1
    environment:
      IOS_VERSION: 16.4
      DEVICE_NAME: iPhone 14 Pro
    steps:
      - checkout
      - run:
          name: Install nvm
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            source ~/.nvm/nvm.sh
      - run:
          name: Remove Node.js version 18.6.0
          command: |
            source ~/.nvm/nvm.sh
            nvm uninstall 18.6.0
            nvm list
            nvm uninstall --lts
            nvm uninstall --latest
      - run:
          name: Install Node.js 20.15.0 and npm directly
          command: |
            # Download Node.js 20.15.0 binaries
            curl -O https://nodejs.org/dist/v20.15.0/node-v20.15.0-darwin-x64.tar.gz

            # Extract the downloaded file
            tar -xzf node-v20.15.0-darwin-x64.tar.gz

            # Move Node.js binaries to a system location
            sudo mv node-v20.15.0-darwin-x64 /usr/local/node-v20.15.0
            sudo ln -s /usr/local/node-v20.15.0/bin/node /usr/local/bin/node
            sudo ln -s /usr/local/node-v20.15.0/bin/npm /usr/local/bin/npm
            sudo ln -s /usr/local/node-v20.15.0/bin/npx /usr/local/bin/npx
      - run:
          name: Verify Node.js Installation
          command: |
            node -v
            npm -v
      - run:
          name: Install Dependencies
          command: npm install
      # Install Appium
      - run:
          name: Install Appium
          command: |
            npm install -g appium
            appium -v
      # Start Appium Server
      - run:
          name: Start Appium Server
          command: |
            appium &
            sleep 5
      # Run Tests
      - run:
          name: Run Tests
          command: |
            npx wdio config/wdio.conf.js
workflows:
  build_and_test:
    jobs:
      - ios
